Repository Sage-Bionetworks/synapseAnnotations, pull requests merged in 2018-05, with the labels that each got.

#223 Added values to tissue
  synapseAnnotations/data/experimentalData.json
Labels: create value, delete value, enhancement

#383 add ssGSEA, GSVA
  synapseAnnotations/data/analysis.json
Labels: create value

#384 add value Enrichr, DEseq2, correct spelling of visualization
  synapseAnnotations/data/analysis.json
Labels: create value, edit key

#385 added value dorsal pallium to tissue
  synapseAnnotations/data/experimentalData.json
Labels: create value
