Repository Sage-Bionetworks/synapseAnnotations, pull requests merged in 2020-05, with the labels that each got.

#596 Add IU to individualIdSource
  synapseAnnotations/data/experimentalData.json
Labels: create value

#598 Schemaorg conversion v2
  synapseAnnotations/ManifestGenerator.py
  synapseAnnotations/MetadataModel.py
  synapseAnnotations/Schema Explorer Demo.ipynb
  synapseAnnotations/SynapseStorage.py
  synapseAnnotations/biothings_schema.jsonld
  synapseAnnotations/config.py
  synapseAnnotations/csv_2_schemaorg.py
  synapseAnnotations/example_manifest.csv
  synapseAnnotations/example_schema.py
  synapseAnnotations/example_schema_usage.py
  synapseAnnotations/jsonld_2_jsonschema.py
  synapseAnnotations/psych_encode_2_biothings.py
  synapseAnnotations/psych_encode_2_biothings_v1.py
  synapseAnnotations/requirements.txt
  synapseAnnotations/sage_annotations_2_biothings.py
  synapseAnnotations/schema_explorer/__init__.py
  synapseAnnotations/schema_explorer/base.py
  synapseAnnotations/schema_generator.py
  synapseAnnotations/schemas/.DS_Store
  synapseAnnotations/schemas/annotations.csv
  synapseAnnotations/schemas/annotations.jsonld
  synapseAnnotations/schemas/biothings_schema.jsonld
  synapseAnnotations/schemas/example.csv
  synapseAnnotations/schemas/example.jsonld
  synapseAnnotations/schemas/masterSageJSONSchema.json
  synapseAnnotations/utils.py
Labels: schema.org conversion

#597 Remove never-used MODEL-AD studies
  synapseAnnotations/data/neuro.json
Labels: delete value

#603 Updates to modelSystemName values
  synapseAnnotations/data/neuro.json
Labels: create value, delete value, edit value

#605 Add PET and Autorad scanners to platform
  synapseAnnotations/data/experimentalData.json
Labels: create value

#604 Add cresyl violet stain as an assay
  synapseAnnotations/data/experimentalData.json
Labels: create value

#606 Add Siemens MRI to platform
  synapseAnnotations/data/experimentalData.json
Labels: create value
